using UnityEngine;
using System.Collections.Generic;

namespace MultiplayerARPG
{
    [DisallowMultipleComponent]
    public abstract partial class BaseUISceneGameplay : MonoBehaviour, IItemUIVisibilityManager, IItemsContainerUIVisibilityManager
    {
        public static BaseUISceneGameplay Singleton { get; private set; }

        [Header("Combat Text")]
        public bool instantiateCombatTextToWorldTransform;
        public Transform combatTextTransform;
        public UICombatText uiCombatTextMiss;
        public UICombatText uiCombatTextNormalDamage;
        public UICombatText uiCombatTextCriticalDamage;
        public UICombatText uiCombatTextBlockedDamage;
        public UICombatText uiCombatTextHpRecovery;
        public UICombatText uiCombatTextMpRecovery;
        public UICombatText uiCombatTextStaminaRecovery;
        public UICombatText uiCombatTextFoodRecovery;
        public UICombatText uiCombatTextWaterRecovery;
        public UICombatText uiCombatTextHpDecrease;
        public UICombatText uiCombatTextMpDecrease;
        public UICombatText uiCombatTextStaminaDecrease;
        public UICombatText uiCombatTextFoodDecrease;
        public UICombatText uiCombatTextWaterDecrease;

        private readonly Dictionary<DamageableEntity, Queue<KeyValuePair<CombatAmountType, int>>> _spawningCombatTexts = new Dictionary<DamageableEntity, Queue<KeyValuePair<CombatAmountType, int>>>();
        private readonly Dictionary<DamageableEntity, float> _spawningCombatTextTimes = new Dictionary<DamageableEntity, float>();

        protected virtual void Awake()
        {
            Singleton = this;
        }

        protected virtual void OnEnable()
        {
            GameInstance.ItemUIVisibilityManager = this;
            GameInstance.ItemsContainerUIVisibilityManager = this;
        }

        protected virtual void OnDisable()
        {
            GameInstance.ItemUIVisibilityManager = null;
            GameInstance.ItemsContainerUIVisibilityManager = null;
        }

        protected virtual void Update()
        {
            float currentTime = Time.unscaledTime;
            KeyValuePair<CombatAmountType, int> combatTextData;
            foreach (DamageableEntity damageableEntity in _spawningCombatTexts.Keys)
            {
                if (damageableEntity == null || _spawningCombatTexts[damageableEntity].Count == 0)
                    continue;

                if (!_spawningCombatTextTimes.ContainsKey(damageableEntity))
                    _spawningCombatTextTimes[damageableEntity] = currentTime;

                if (currentTime - _spawningCombatTextTimes[damageableEntity] >= 0.1f)
                {
                    _spawningCombatTextTimes[damageableEntity] = currentTime;
                    combatTextData = _spawningCombatTexts[damageableEntity].Dequeue();
                    SpawnCombatText(damageableEntity.CombatTextTransform, combatTextData.Key, combatTextData.Value);
                }
            }
        }

        public void PrepareCombatText(DamageableEntity damageableEntity, CombatAmountType combatAmountType, int amount)
        {
            if (Vector3.Distance(GameInstance.PlayingCharacterEntity.EntityTransform.position, damageableEntity.EntityTransform.position) > GameInstance.Singleton.combatTextDistance)
                return;

            if (!_spawningCombatTexts.ContainsKey(damageableEntity))
                _spawningCombatTexts[damageableEntity] = new Queue<KeyValuePair<CombatAmountType, int>>();
            _spawningCombatTexts[damageableEntity].Enqueue(new KeyValuePair<CombatAmountType, int>(combatAmountType, amount));
        }

        public void SpawnCombatText(Transform followingTransform, CombatAmountType combatAmountType, int amount)
        {
            switch (combatAmountType)
            {
                case CombatAmountType.Miss:
                    SpawnCombatText(followingTransform, uiCombatTextMiss, amount);
                    break;
                case CombatAmountType.NormalDamage:
                    SpawnCombatText(followingTransform, uiCombatTextNormalDamage, amount);
                    break;
                case CombatAmountType.CriticalDamage:
                    SpawnCombatText(followingTransform, uiCombatTextCriticalDamage, amount);
                    break;
                case CombatAmountType.BlockedDamage:
                    SpawnCombatText(followingTransform, uiCombatTextBlockedDamage, amount);
                    break;
                case CombatAmountType.HpRecovery:
                    SpawnCombatText(followingTransform, uiCombatTextHpRecovery, amount);
                    break;
                case CombatAmountType.MpRecovery:
                    SpawnCombatText(followingTransform, uiCombatTextMpRecovery, amount);
                    break;
                case CombatAmountType.StaminaRecovery:
                    SpawnCombatText(followingTransform, uiCombatTextStaminaRecovery, amount);
                    break;
                case CombatAmountType.FoodRecovery:
                    SpawnCombatText(followingTransform, uiCombatTextFoodRecovery, amount);
                    break;
                case CombatAmountType.WaterRecovery:
                    SpawnCombatText(followingTransform, uiCombatTextWaterRecovery, amount);
                    break;
                case CombatAmountType.HpDecrease:
                    SpawnCombatText(followingTransform, uiCombatTextHpDecrease, amount);
                    break;
                case CombatAmountType.MpDecrease:
                    SpawnCombatText(followingTransform, uiCombatTextMpDecrease, amount);
                    break;
                case CombatAmountType.StaminaDecrease:
                    SpawnCombatText(followingTransform, uiCombatTextStaminaDecrease, amount);
                    break;
                case CombatAmountType.FoodDecrease:
                    SpawnCombatText(followingTransform, uiCombatTextFoodDecrease, amount);
                    break;
                case CombatAmountType.WaterDecrease:
                    SpawnCombatText(followingTransform, uiCombatTextWaterDecrease, amount);
                    break;
            }
        }

        public void SpawnCombatText(Transform followingTransform, UICombatText prefab, int amount)
        {
            if (prefab == null)
                return;

            UICombatText combatText;
            if (!instantiateCombatTextToWorldTransform && combatTextTransform)
            {
                combatText = Instantiate(prefab, combatTextTransform);
                combatText.transform.localScale = Vector3.one;
                combatText.gameObject.GetOrAddComponent<UIFollowWorldObject>().TargetObject = followingTransform;
            }
            else
            {
                combatText = Instantiate(prefab);
                combatText.transform.position = followingTransform.position;
            }
            combatText.Amount = amount;
        }

        public virtual bool IsBlockController()
        {
            if (UISceneGlobal.Singleton.uiMessageDialog.IsVisible() ||
                UISceneGlobal.Singleton.uiInputDialog.IsVisible() ||
                UISceneGlobal.Singleton.uiPasswordDialog.IsVisible())
                return true;

            if (UIBlockController.IsBlockController())
                return true;

            return false;
        }

        public virtual bool IsPointerOverUIObject()
        {
            return false;
        }

        // Abstract functions
        public abstract void SetTargetEntity(BaseGameEntity entity);
        public abstract void SetActivePlayerCharacter(BasePlayerCharacterEntity playerCharacter);
        public abstract void HideQuestRewardItemSelection();
        public abstract void HideNpcDialog();
        public abstract void ShowConstructBuildingDialog(BuildingEntity buildingEntity);
        public abstract void HideConstructBuildingDialog();
        public abstract void ShowCurrentBuildingDialog(BuildingEntity buildingEntity);
        public abstract void HideCurrentBuildingDialog();
        public abstract bool IsShopDialogVisible();
        public abstract bool IsRefineItemDialogVisible();
        public abstract bool IsDismantleItemDialogVisible();
        public abstract bool IsRepairItemDialogVisible();
        public abstract bool IsEnhanceSocketItemDialogVisible();
        public abstract bool IsStorageDialogVisible();
        public abstract bool IsItemsContainerDialogVisible();
        public abstract bool IsDealingDialogVisibleWithDealingState();
        public abstract void ShowRefineItemDialog(InventoryType inventoryType, int indexOfData);
        public abstract void ShowDismantleItemDialog(InventoryType inventoryType, int indexOfData);
        public abstract void ShowRepairItemDialog(InventoryType inventoryType, int indexOfData);
        public abstract void ShowEnhanceSocketItemDialog(InventoryType inventoryType, int indexOfData);
        public abstract void ShowStorageDialog(StorageType storageType, string storageOwnerId, uint objectId, int weightLimit, int slotLimit);
        public abstract void HideStorageDialog();
        public abstract void ShowItemsContainerDialog(ItemsContainerEntity itemsContainerEntity);
        public abstract void HideItemsContainerDialog();
        public abstract void ShowWorkbenchDialog(WorkbenchEntity workbenchEntity);
        public abstract void ShowCraftingQueueItemsDialog(ICraftingQueueSource source);
        public abstract void OnControllerSetup(BasePlayerCharacterEntity characterEntity);
        public abstract void OnControllerDesetup(BasePlayerCharacterEntity characterEntity);
        // Abstract properties
        public abstract ItemsContainerEntity ItemsContainerEntity { get; }
    }
}
